version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - db
      - cache
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_task
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - QUEUE_CONNECTION=redis

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_task
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network

  cache:
    image: redis:7-alpine
    container_name: laravel-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - db
      - cache
    networks:
      - laravel-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_task
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - QUEUE_CONNECTION=redis

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
